run:
  tests: true
  timeout: 5m
  go: "1.20"

linters:
  enable:
    - errcheck

issues:
  exclude-use-default: false

linters-settings:
  errcheck:
    # exclude: errcheck-exclude.txt
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write
