name: Test

on:
  push:
    branches:
      - master
    paths:
      - "**/*.go"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.go"

jobs:
  audit:
    name: Auditing the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20.x

      - name: Run Audit
        run: |
          make lint
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Add coverage.out to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: coverage-out
          path: ./coverage.out

      - name: Add coverage.html to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: coverage-html
          path: ./coverage.html
